server:
  port: 8082
  address: 0.0.0.0
  public-ip: ${SERVER_PUBLIC_IP:}

frontend:
  port: ${FRONTEND_PORT:3002}

spring:
  application:
    name: BLITCoding
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1111}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:hotel_booking_db}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: rRaAQAHZ4J0PN/fa6H8gTRYqr5n/eWa9ADqh8jwzBqY=
  expiration: 28800000  # 8 hours (8 * 60 * 60 * 1000)
